
export const ABSTRACT_NOUNS = [
  "the geometry of a secret", "the weight of silence", "the architecture of grief", 
  "the velocity of becoming", "the grammar of loss", "the mathematics of hope", 
  "the topology of memory", "the syntax of longing", "the rhythm of survival", 
  "the texture of time", "the cartography of the heart", "the physics of longing", 
  "the algebra of forgiveness", "the geometry of belonging", "the music of sorrow", 
  "the language of the unsaid", "the blueprint of becoming", "the skeleton of a dream", 
  "the fossil of a feeling", "the constellation of your fears", "the archaeology of joy", 
  "the seismology of change", "the meteorology of the soul", "the botany of grief", 
  "the ornithology of hope", "the entomology of transformation", "the mineralogy of time", 
  "the oceanography of emotion", "the astronomy of longing", "the geology of the heart", 
  "the biology of becoming", "the chemistry of connection", "the thermodynamics of love", 
  "the mechanics of memory", "the optics of truth", "the acoustics of silence", 
  "the dynamics of change", "the statics of stillness", "the kinetics of becoming", 
  "the potential of tomorrow", "the momentum of change", "the gravity of consequence", 
  "the friction of resistance", "the elasticity of hope", "the viscosity of time", 
  "the density of meaning", "the porosity of the soul", "the luminosity of truth", 
  "the opacity of mystery"
];

// Replaced simple strings with tagged objects
export const CONCRETE_NOUNS = {
  Small: [
    { text: "the second-to-last leaf", tags: ['Impermanence', 'Nature', 'Transition', 'Loss'], scale: 'small', rarity: 'rare' },
    { text: "a debt paid in shadow", tags: ['Memory', 'Darkness', 'Loss', 'Shame'], scale: 'small', rarity: 'rare' },
    { text: "the rust on a gate", tags: ['Decay', 'Time', 'Boundary', 'Texture'], scale: 'small', rarity: 'common' },
    { text: "the fingerprint on glass", tags: ['Touch', 'Presence', 'Memory', 'Impermanence'], scale: 'small', rarity: 'common' },
    { text: "the crease in a letter", tags: ['Memory', 'Touch', 'Love', 'Communication'], scale: 'small', rarity: 'common' },
    { text: "the scar on a tree", tags: ['Time', 'Nature', 'Wound', 'Healing'], scale: 'small', rarity: 'common' },
    { text: "the echo in an empty room", tags: ['Sound', 'Solitude', 'Loss', 'Space'], scale: 'small', rarity: 'rare' },
    { text: "the stain that won't wash out", tags: ['Shame', 'Permanence', 'Memory', 'Regret'], scale: 'small', rarity: 'rare' },
    { text: "the thread pulled from a sweater", tags: ['Unraveling', 'Texture', 'Fragility', 'Loss'], scale: 'small', rarity: 'common' },
    { text: "the ash in a fireplace", tags: ['Fire', 'End', 'Transformation', 'Warmth'], scale: 'small', rarity: 'common' },
    { text: "the dust on a photograph", tags: ['Time', 'Memory', 'Neglect', 'Nostalgia'], scale: 'small', rarity: 'common' },
    { text: "the crack in a mirror", tags: ['Fracture', 'Identity', 'Sight', 'Change'], scale: 'small', rarity: 'rare' },
    { text: "the knot in a rope", tags: ['Tension', 'Strength', 'Touch', 'Connection'], scale: 'small', rarity: 'common' },
    { text: "the hole in a pocket", tags: ['Loss', 'Empty', 'Texture', 'Neglect'], scale: 'small', rarity: 'common' },
    { text: "the mark on a wall", tags: ['Memory', 'Home', 'Time', 'Presence'], scale: 'small', rarity: 'common' },
    { text: "the dent in a can", tags: ['Imperfection', 'Touch', 'Time', 'Reality'], scale: 'small', rarity: 'common' },
    { text: "the tear in a page", tags: ['Fragility', 'Story', 'Wound', 'Touch'], scale: 'small', rarity: 'common' },
    { text: "the burn mark on wood", tags: ['Fire', 'Scar', 'Memory', 'Heat'], scale: 'small', rarity: 'common' },
    { text: "the water ring on a table", tags: ['Carelessness', 'Memory', 'Liquid', 'Home'], scale: 'small', rarity: 'common' },
    { text: "the scratch on glass", tags: ['Damage', 'Surface', 'Sight', 'Sound'], scale: 'small', rarity: 'common' },
    { text: "the indent in a pillow", tags: ['Sleep', 'Presence', 'Absence', 'Comfort'], scale: 'small', rarity: 'rare' },
    { text: "the smudge on a window", tags: ['Blur', 'Sight', 'Touch', 'Obstruction'], scale: 'small', rarity: 'common' },
    { text: "the nick in a blade", tags: ['Use', 'Violence', 'History', 'Metal'], scale: 'small', rarity: 'common' },
    { text: "the fray at an edge", tags: ['Wear', 'Time', 'Texture', 'End'], scale: 'small', rarity: 'common' },
    { text: "the spot on a shirt", tags: ['Mistake', 'Daily', 'Memory', 'Self'], scale: 'small', rarity: 'common' },
    { text: "the chip in a cup", tags: ['Imperfection', 'Home', 'Use', 'Fragility'], scale: 'small', rarity: 'common' },
    { text: "the bend in a corner", tags: ['Direction', 'Change', 'Space', 'Geometry'], scale: 'small', rarity: 'common' },
    { text: "the wrinkle in fabric", tags: ['Age', 'Use', 'Texture', 'Comfort'], scale: 'small', rarity: 'common' },
    { text: "the callus on a hand", tags: ['Work', 'Touch', 'Growth', 'Protection'], scale: 'small', rarity: 'rare' },
    { text: "the scar on skin", tags: ['Wound', 'Healing', 'Memory', 'Body'], scale: 'small', rarity: 'rare' }
  ],
  Medium: [
    { text: "the rim of your favorite cup", tags: ['Home', 'Warmth', 'Ritual', 'Touch'], scale: 'medium', rarity: 'common' },
    { text: "the garden you tend", tags: ['Growth', 'Nature', 'Care', 'Patience'], scale: 'medium', rarity: 'common' },
    { text: "the threshold of your home", tags: ['Transition', 'Safety', 'Welcome', 'Boundary'], scale: 'medium', rarity: 'rare' },
    { text: "the first loaf of bread", tags: ['Creation', 'Nourishment', 'Smell', 'Warmth'], scale: 'medium', rarity: 'common' },
    { text: "a hand-knit blanket", tags: ['Comfort', 'Warmth', 'Touch', 'Love'], scale: 'medium', rarity: 'common' },
    { text: "the stain on the kitchen table", tags: ['Memory', 'Family', 'Home', 'Time'], scale: 'medium', rarity: 'common' },
    { text: "the worn handle of a wooden spoon", tags: ['Use', 'Cooking', 'Touch', 'Time'], scale: 'medium', rarity: 'common' },
    { text: "the corner of a well-loved quilt", tags: ['Comfort', 'Sleep', 'Texture', 'History'], scale: 'medium', rarity: 'common' },
    { text: "the inside of a recipe box", tags: ['Legacy', 'Family', 'Taste', 'Memory'], scale: 'medium', rarity: 'common' },
    { text: "a jar of preserved fruit", tags: ['Summer', 'Taste', 'Storage', 'Patience'], scale: 'medium', rarity: 'common' },
    { text: "the spine of a cookbook", tags: ['Knowledge', 'Use', 'Home', 'Reading'], scale: 'medium', rarity: 'common' },
    { text: "the seat by the window", tags: ['Solitude', 'Sight', 'Reflection', 'Rest'], scale: 'medium', rarity: 'common' },
    { text: "a vase of wildflowers", tags: ['Nature', 'Beauty', 'Impermanence', 'Color'], scale: 'medium', rarity: 'common' },
    { text: "the hem of an apron", tags: ['Work', 'Domesticity', 'Fabric', 'Care'], scale: 'medium', rarity: 'common' },
    { text: "the back of a kitchen chair", tags: ['Support', 'Rest', 'Home', 'Furniture'], scale: 'medium', rarity: 'common' },
    { text: "a loaf still warm from the oven", tags: ['Warmth', 'Smell', 'Comfort', 'Life'], scale: 'medium', rarity: 'common' },
    { text: "the edge of a cutting board", tags: ['Preparation', 'Food', 'Wood', 'Action'], scale: 'medium', rarity: 'common' },
    { text: "a candle half-burned", tags: ['Light', 'Time', 'Atmosphere', 'Warmth'], scale: 'medium', rarity: 'common' },
    { text: "the corner of a linen closet", tags: ['Order', 'Smell', 'Softness', 'Hidden'], scale: 'medium', rarity: 'common' },
    { text: "the threshold between rooms", tags: ['Transition', 'Space', 'Movement', 'Choice'], scale: 'medium', rarity: 'common' },
    { text: "the back of a door", tags: ['Privacy', 'Closing', 'Barrier', 'Safety'], scale: 'medium', rarity: 'common' },
    { text: "the inside of a drawer", tags: ['Secrets', 'Storage', 'Hidden', 'Order'], scale: 'medium', rarity: 'common' },
    { text: "the corner of a shelf", tags: ['Display', 'Dust', 'Space', 'Structure'], scale: 'medium', rarity: 'common' },
    { text: "the edge of a bed", tags: ['Sleep', 'Intimacy', 'Rest', 'Rising'], scale: 'medium', rarity: 'common' },
    { text: "the back of a chair", tags: ['Support', 'Posture', 'Rest', 'Furniture'], scale: 'medium', rarity: 'common' },
    { text: "the rim of a sink", tags: ['Water', 'Cleaning', 'Daily', 'Routine'], scale: 'medium', rarity: 'common' },
    { text: "the corner of a counter", tags: ['Meeting', 'Surface', 'Kitchen', 'Place'], scale: 'medium', rarity: 'common' },
    { text: "the edge of a table", tags: ['Gathering', 'Family', 'Surface', 'Support'], scale: 'medium', rarity: 'common' },
    { text: "the back of a stove", tags: ['Heat', 'Cooking', 'Hidden', 'Grease'], scale: 'medium', rarity: 'common' },
    { text: "the inside of a cupboard", tags: ['Darkness', 'Storage', 'Vessels', 'Plenty'], scale: 'medium', rarity: 'common' }
  ],
  Large: [
    { text: "a bridge across the divide", tags: ['Connection', 'Travel', 'Structure', 'Distance'], scale: 'large', rarity: 'mythic' },
    { text: "the silent machinery of the future", tags: ['Time', 'Destiny', 'Mechanism', 'Fate'], scale: 'large', rarity: 'mythic' },
    { text: "a law written in light", tags: ['Truth', 'Authority', 'Light', 'Justice'], scale: 'large', rarity: 'mythic' },
    { text: "the lintel of your home", tags: ['Foundation', 'Shelter', 'Structure', 'Entrance'], scale: 'large', rarity: 'rare' },
    { text: "the first page of your story", tags: ['Beginning', 'Narrative', 'Life', 'Potential'], scale: 'large', rarity: 'rare' },
    { text: "the threshold you're crossing", tags: ['Transition', 'Change', 'Movement', 'Courage'], scale: 'large', rarity: 'rare' },
    { text: "the foundation you're laying", tags: ['Building', 'Future', 'Strength', 'Ground'], scale: 'large', rarity: 'rare' },
    { text: "the horizon you're claiming", tags: ['Distance', 'Hope', 'Vision', 'Ownership'], scale: 'large', rarity: 'mythic' },
    { text: "a monument to your own becoming", tags: ['Identity', 'Growth', 'Memory', 'Stone'], scale: 'large', rarity: 'mythic' },
    { text: "the cornerstone of your empire", tags: ['Power', 'Foundation', 'Ambition', 'Structure'], scale: 'large', rarity: 'mythic' },
    { text: "a door that opens inward", tags: ['Self', 'Discovery', 'Interior', 'Entrance'], scale: 'large', rarity: 'rare' },
    { text: "the spine of history", tags: ['Time', 'Past', 'Structure', 'Support'], scale: 'large', rarity: 'mythic' },
    { text: "a contract with tomorrow", tags: ['Future', 'Promise', 'Time', 'Hope'], scale: 'large', rarity: 'rare' },
    { text: "the architecture of your dreams", tags: ['Vision', 'Structure', 'Imagination', 'Building'], scale: 'large', rarity: 'mythic' },
    { text: "a beacon for those who follow", tags: ['Light', 'Leadership', 'Legacy', 'Hope'], scale: 'large', rarity: 'mythic' },
    { text: "the weight of your own gravity", tags: ['Self', 'Power', 'Presence', 'Influence'], scale: 'large', rarity: 'rare' },
    { text: "a crown you're forging", tags: ['Authority', 'Creation', 'Power', 'Identity'], scale: 'large', rarity: 'mythic' },
    { text: "the map of your own making", tags: ['Direction', 'Choice', 'Freedom', 'Creation'], scale: 'large', rarity: 'rare' },
    { text: "a temple built from your own hands", tags: ['Sacred', 'Work', 'Creation', 'Body'], scale: 'large', rarity: 'mythic' },
    { text: "the echo that will outlast you", tags: ['Legacy', 'Time', 'Sound', 'Impermanence'], scale: 'large', rarity: 'mythic' },
    { text: "the cathedral of your becoming", tags: ['Sacred', 'Growth', 'Structure', 'Spirit'], scale: 'large', rarity: 'mythic' },
    { text: "the fortress of your heart", tags: ['Protection', 'Love', 'Defense', 'Interior'], scale: 'large', rarity: 'rare' },
    { text: "the palace of your mind", tags: ['Thought', 'Wealth', 'Interior', 'Memory'], scale: 'large', rarity: 'mythic' },
    { text: "the kingdom you're building", tags: ['Ambition', 'Creation', 'Power', 'Domain'], scale: 'large', rarity: 'mythic' },
    { text: "the empire of your own making", tags: ['Power', 'Control', 'Creation', 'World'], scale: 'large', rarity: 'mythic' },
    { text: "the monument to your resistance", tags: ['Strength', 'Defiance', 'Memory', 'Stone'], scale: 'large', rarity: 'mythic' },
    { text: "the tower of your ambition", tags: ['Height', 'Desire', 'Goals', 'Structure'], scale: 'large', rarity: 'mythic' },
    { text: "the citadel of your soul", tags: ['Spirit', 'Protection', 'Core', 'Sacred'], scale: 'large', rarity: 'mythic' },
    { text: "the colossus of your becoming", tags: ['Size', 'Growth', 'Power', 'Statue'], scale: 'large', rarity: 'mythic' },
    { text: "the pyramid of your legacy", tags: ['Time', 'Death', 'Memory', 'History'], scale: 'large', rarity: 'mythic' }
  ]
};

export const TEMPORAL_SENTIMENTS = [
  "as the sun sets on this chapter", "in the moment before everything changed", 
  "when the clock stopped", "in the space between then and now", "as the last light fades", 
  "in the hour of reckoning", "when you were still becoming", "at the threshold of tomorrow", 
  "in the pause between heartbeats", "as time folds back on itself", 
  "in the instant before the fall", "when the world held its breath", "at the edge of forever", 
  "in the moment of recognition", "as the seasons turn", "when the tide goes out", 
  "in the space where time bends", "at the crossroads of your life", "in the hour before dawn", 
  "when the night is deepest", "at the turning of the year", 
  "in the space between sleep and waking", "as the bell tolls", "when the door closes", 
  "in the moment of surrender", "at the threshold of the unknown", "when the veil lifts", 
  "in the space between breaths", "as the wheel turns", "when the music stops", 
  "in the moment of truth", "at the edge of the abyss", "when the light breaks through", 
  "in the space of becoming", "as the river flows", "when the storm passes", 
  "in the moment of grace", "at the threshold of transformation", "when the seed germinates", 
  "in the space of healing", "as the wound closes", "when the scar forms", 
  "in the moment of forgiveness", "at the threshold of homecoming", 
  "when the circle closes", "in the space of belonging", "as the dawn breaks", 
  "when the night ends", "in the moment of arrival"
];

// Deprecated in favor of HIGH_CONTEXT_ACTIONS for advanced prompts, but kept for fallback
export const PHILOSOPHICAL_ACTIONS = {
  common: [
    { text: "to mark", rarity: "common" }, { text: "to remember", rarity: "common" }, 
    { text: "to honor", rarity: "common" }, { text: "to claim", rarity: "common" }, 
    { text: "to witness", rarity: "common" }, { text: "to hold", rarity: "common" }, 
    { text: "to carry", rarity: "common" }, { text: "to build", rarity: "common" }, 
    { text: "to create", rarity: "common" }, { text: "to speak", rarity: "common" }, 
    { text: "to listen", rarity: "common" }, { text: "to learn", rarity: "common" }, 
    { text: "to grow", rarity: "common" }, { text: "to heal", rarity: "common" }, 
    { text: "to forgive", rarity: "common" }, { text: "to love", rarity: "common" }, 
    { text: "to trust", rarity: "common" }, { text: "to believe", rarity: "common" }, 
    { text: "to hope", rarity: "common" }, { text: "to dream", rarity: "common" }
  ],
  rare: [
    { text: "to transmute", rarity: "rare" }, { text: "to absolve", rarity: "rare" }, 
    { text: "to resurrect", rarity: "rare" }, { text: "to bury", rarity: "rare" }, 
    { text: "to anchor", rarity: "rare" }, { text: "to dissolve", rarity: "rare" }, 
    { text: "to consecrate", rarity: "rare" }, { text: "to rebel", rarity: "rare" }, 
    { text: "to reconcile", rarity: "rare" }, { text: "to inscribe", rarity: "rare" }, 
    { text: "to unearth", rarity: "rare" }, { text: "to sanctify", rarity: "rare" }, 
    { text: "to illuminate", rarity: "rare" }, { text: "to transform", rarity: "rare" }, 
    { text: "to transcend", rarity: "rare" }, { text: "to surrender", rarity: "rare" }, 
    { text: "to reclaim", rarity: "rare" }, { text: "to awaken", rarity: "rare" }, 
    { text: "to ascend", rarity: "rare" }, { text: "to descend", rarity: "rare" }
  ],
  mythic: [
    { text: "to resurrect", rarity: "mythic" }, { text: "to annihilate", rarity: "mythic" }, 
    { text: "to deify", rarity: "mythic" }, { text: "to obliterate", rarity: "mythic" }, 
    { text: "to apothesize", rarity: "mythic" }, { text: "to transcend mortality", rarity: "mythic" }, 
    { text: "to write yourself into legend", rarity: "mythic" }, { text: "to become eternal", rarity: "mythic" }, 
    { text: "to shatter the void", rarity: "mythic" }, { text: "to birth a new world", rarity: "mythic" }, 
    { text: "to dissolve into everything", rarity: "mythic" }, { text: "to claim your divinity", rarity: "mythic" }, 
    { text: "to break the chains of time", rarity: "mythic" }, { text: "to become the storm", rarity: "mythic" }, 
    { text: "to write yourself into the void", rarity: "mythic" }
  ]
};

export const HIGH_CONTEXT_ACTIONS = [
  // Light Intensity
  { text: "to stitch together", rarity: "common", intensity: "light", category: "Repair" },
  { text: "to weave", rarity: "common", intensity: "light", category: "Creation" },
  { text: "to apologize to", rarity: "common", intensity: "light", category: "Relational" },
  { text: "to reconcile", rarity: "common", intensity: "light", category: "Relational" },
  { text: "to germinate", rarity: "common", intensity: "light", category: "Growth" },
  { text: "to ferment", rarity: "common", intensity: "light", category: "Transformation" },
  { text: "to anchor yourself to", rarity: "common", intensity: "light", category: "Stability" },
  { text: "to illuminate", rarity: "common", intensity: "light", category: "Revelation" },
  { text: "to excavate", rarity: "common", intensity: "light", category: "Discovery" },
  { text: "to unravel", rarity: "common", intensity: "light", category: "Destruction" },

  // Medium Intensity
  { text: "to exhumed", rarity: "rare", intensity: "medium", category: "Discovery" },
  { text: "to consecrate", rarity: "rare", intensity: "medium", category: "Sacred" },
  { text: "to inscribe", rarity: "rare", intensity: "medium", category: "Creation" },
  { text: "to absolve", rarity: "rare", intensity: "medium", category: "Forgiveness" },
  { text: "to reclaim", rarity: "rare", intensity: "medium", category: "Power" },
  { text: "to sanctify", rarity: "rare", intensity: "medium", category: "Sacred" },
  { text: "to suture", rarity: "rare", intensity: "medium", category: "Healing" },
  { text: "to crystallize", rarity: "rare", intensity: "medium", category: "Transformation" },
  { text: "to calcify", rarity: "rare", intensity: "medium", category: "Stagnation" },
  { text: "to proliferate", rarity: "rare", intensity: "medium", category: "Growth" },

  // Heavy Intensity
  { text: "to transmute", rarity: "mythic", intensity: "heavy", category: "Alchemy" },
  { text: "to dissolve into", rarity: "mythic", intensity: "heavy", category: "Surrender" },
  { text: "to resurrect", rarity: "mythic", intensity: "heavy", category: "Life" },
  { text: "to lacerate", rarity: "mythic", intensity: "heavy", category: "Violence" },
  { text: "to ossify", rarity: "mythic", intensity: "heavy", category: "Stagnation" },
  { text: "to petrify", rarity: "mythic", intensity: "heavy", category: "Fear" },
  { text: "to liquefy", rarity: "mythic", intensity: "heavy", category: "Transformation" },
  { text: "to atrophy", rarity: "mythic", intensity: "heavy", category: "Decay" },

  // Transcendent Intensity
  { text: "to deify", rarity: "mythic", intensity: "transcendent", category: "Divinity" },
  { text: "to obliterate", rarity: "mythic", intensity: "transcendent", category: "Destruction" },
  { text: "to apothesize", rarity: "mythic", intensity: "transcendent", category: "Divinity" },
  { text: "to dissolve into everything", rarity: "mythic", intensity: "transcendent", category: "Union" },
  { text: "to write yourself into the void", rarity: "mythic", intensity: "transcendent", category: "Creation" },
  { text: "to break the chains of time", rarity: "mythic", intensity: "transcendent", category: "Freedom" },
  { text: "to become the storm", rarity: "mythic", intensity: "transcendent", category: "Power" }
];
